package com.appsingularity.postman.compiler.handlers;

import com.appsingularity.postman.compiler.PostmanProcessor;
import com.google.common.base.Joiner;
import com.google.testing.compile.JavaFileObjects;

import org.junit.Test;

import javax.tools.JavaFileObject;

import static com.google.common.truth.Truth.assertAbout;
import static com.google.testing.compile.JavaSourceSubjectFactory.javaSource;

/**
 * Make sure we can process lists of non primitives
 */
public class PrimitiveListTest {


    @Test
    public void testPrimitiveLists() {
        JavaFileObject source = JavaFileObjects.forSourceString("test.Model",
                Joiner.on('\n').join(
                        "package test;",
                        "",
                        "import com.appsingularity.postman.Postman;",
                        "import com.appsingularity.postman.annotations.PostmanEnabled;",
                        "import android.os.Parcel;",
                        "import android.os.Parcelable;",
                        "import java.util.List;",
                        "",
                        "@PostmanEnabled",
                        "public class Model implements Parcelable {",
                        "   List<Boolean> mBoolean;",
                        "   List<Character> mChar;",
                        "   List<Byte> mByte;",
                        "   List<Short> mShort;",
                        "   List<Integer> mInt;",
                        "   List<Long> mLong;",
                        "   List<Float> mFloat;",
                        "   List<Double> mDouble;",
                        "",
                        "   protected Model(Parcel in) {",
                        "     Postman.receive(this, in);",
                        "  }",
                        "",
                        "  @Override",
                        "  public void writeToParcel(Parcel dest, int flags) {",
                        "    Postman.ship(this, dest, flags);",
                        "  }",
                        "",
                        "  @Override",
                        "  public int describeContents() {",
                        "    return 0;",
                        "  }",
                        "",
                        "  public static final Parcelable.Creator<Model> CREATOR = new Parcelable.Creator<Model>() {",
                        "    @Override",
                        "    public Model createFromParcel(Parcel in) {",
                        "      return new Model(in);",
                        "    }",
                        "",
                        "    @Override",
                        "    public Model[] newArray(int size) {",
                        "      return new Model[size];",
                        "    }",
                        "  };",
                        "}"
                ));
        JavaFileObject expectedSource = JavaFileObjects.forSourceString("test/Model$$Postman",
                Joiner.on('\n').join(
                        "// Generated code from Postman. Do not modify!",
                        "package test;",
                        "",
                        "import com.appsingularity.postman.internal.BasePostman;",
                        "import java.lang.Override;",
                        "",
                        "public final class Model$$Postman extends BasePostman<Model> {",
                        "   @Override",
                        "   public void ship(final Model source, final android.os.Parcel dest, int flags) {",
                        "     if (source.mBoolean != null) {",
                        "       dest.writeByte((byte) 1);",
                        "       dest.writeList(source.mBoolean);",
                        "     } else {",
                        "       dest.writeByte((byte) 0);",
                        "     }",
                        "     if (source.mChar != null) {",
                        "       dest.writeByte((byte) 1);",
                        "       dest.writeList(source.mChar);",
                        "     } else {",
                        "       dest.writeByte((byte) 0);",
                        "     }",
                        "     if (source.mByte != null) {",
                        "       dest.writeByte((byte) 1);",
                        "       dest.writeList(source.mByte);",
                        "     } else {",
                        "       dest.writeByte((byte) 0);",
                        "     }",
                        "     if (source.mShort != null) {",
                        "       dest.writeByte((byte) 1);",
                        "       dest.writeList(source.mShort);",
                        "     } else {",
                        "       dest.writeByte((byte) 0);",
                        "     }",
                        "     if (source.mInt != null) {",
                        "       dest.writeByte((byte) 1);",
                        "       dest.writeList(source.mInt);",
                        "     } else {",
                        "       dest.writeByte((byte) 0);",
                        "     }",
                        "     if (source.mLong != null) {",
                        "       dest.writeByte((byte) 1);",
                        "       dest.writeList(source.mLong);",
                        "     } else {",
                        "       dest.writeByte((byte) 0);",
                        "     }",
                        "     if (source.mFloat != null) {",
                        "       dest.writeByte((byte) 1);",
                        "       dest.writeList(source.mFloat);",
                        "     } else {",
                        "       dest.writeByte((byte) 0);",
                        "     }",
                        "     if (source.mDouble != null) {",
                        "       dest.writeByte((byte) 1);",
                        "       dest.writeList(source.mDouble);",
                        "     } else {",
                        "       dest.writeByte((byte) 0);",
                        "     }",
                        "   }",
                        "",
                        "   @Override",
                        "   public void receive(final Model target, final android.os.Parcel in) {",
                        "     if (in.readByte() == 1) {",
                        "       target.mBoolean = new java.util.ArrayList<>();",
                        "       in.readList(target.mBoolean, java.util.List.class.getClassLoader());",
                        "     }",
                        "     if (in.readByte() == 1) {",
                        "       target.mChar = new java.util.ArrayList<>();",
                        "       in.readList(target.mChar, java.util.List.class.getClassLoader());",
                        "     }",
                        "     if (in.readByte() == 1) {",
                        "       target.mByte = new java.util.ArrayList<>();",
                        "       in.readList(target.mByte, java.util.List.class.getClassLoader());",
                        "     }",
                        "     if (in.readByte() == 1) {",
                        "       target.mShort = new java.util.ArrayList<>();",
                        "       in.readList(target.mShort, java.util.List.class.getClassLoader());",
                        "     }",
                        "     if (in.readByte() == 1) {",
                        "       target.mInt = new java.util.ArrayList<>();",
                        "       in.readList(target.mInt, java.util.List.class.getClassLoader());",
                        "     }",
                        "     if (in.readByte() == 1) {",
                        "       target.mLong = new java.util.ArrayList<>();",
                        "       in.readList(target.mLong, java.util.List.class.getClassLoader());",
                        "     }",
                        "     if (in.readByte() == 1) {",
                        "       target.mFloat = new java.util.ArrayList<>();",
                        "       in.readList(target.mFloat, java.util.List.class.getClassLoader());",
                        "     }",
                        "     if (in.readByte() == 1) {",
                        "       target.mDouble = new java.util.ArrayList<>();",
                        "       in.readList(target.mDouble, java.util.List.class.getClassLoader());",
                        "     }",
                        "   }",
                        "}"
                ));


        assertAbout(javaSource()).that(source)
                .processedWith(new PostmanProcessor())
                .compilesWithoutError()
                .and()
                .generatesSources(expectedSource);
    }


    @Test
    public void testPrimitiveArrayLists() {
        JavaFileObject source = JavaFileObjects.forSourceString("test.Model",
                Joiner.on('\n').join(
                        "package test;",
                        "",
                        "import com.appsingularity.postman.Postman;",
                        "import com.appsingularity.postman.annotations.PostmanEnabled;",
                        "import android.os.Parcel;",
                        "import android.os.Parcelable;",
                        "import java.util.ArrayList;",
                        "",
                        "@PostmanEnabled",
                        "public class Model implements Parcelable {",
                        "   ArrayList<Boolean> mBoolean;",
                        "   ArrayList<Character> mChar;",
                        "   ArrayList<Byte> mByte;",
                        "   ArrayList<Short> mShort;",
                        "   ArrayList<Integer> mInt;",
                        "   ArrayList<Long> mLong;",
                        "   ArrayList<Float> mFloat;",
                        "   ArrayList<Double> mDouble;",
                        "",
                        "   protected Model(Parcel in) {",
                        "     Postman.receive(this, in);",
                        "  }",
                        "",
                        "  @Override",
                        "  public void writeToParcel(Parcel dest, int flags) {",
                        "    Postman.ship(this, dest, flags);",
                        "  }",
                        "",
                        "  @Override",
                        "  public int describeContents() {",
                        "    return 0;",
                        "  }",
                        "",
                        "  public static final Parcelable.Creator<Model> CREATOR = new Parcelable.Creator<Model>() {",
                        "    @Override",
                        "    public Model createFromParcel(Parcel in) {",
                        "      return new Model(in);",
                        "    }",
                        "",
                        "    @Override",
                        "    public Model[] newArray(int size) {",
                        "      return new Model[size];",
                        "    }",
                        "  };",
                        "}"
                ));
        JavaFileObject expectedSource = JavaFileObjects.forSourceString("test/Model$$Postman",
                Joiner.on('\n').join(
                        "// Generated code from Postman. Do not modify!",
                        "package test;",
                        "",
                        "import com.appsingularity.postman.internal.BasePostman;",
                        "import java.lang.Override;",
                        "",
                        "public final class Model$$Postman extends BasePostman<Model> {",
                        "   @Override",
                        "   public void ship(final Model source, final android.os.Parcel dest, int flags) {",
                        "     if (source.mBoolean != null) {",
                        "       dest.writeByte((byte) 1);",
                        "       dest.writeList(source.mBoolean);",
                        "     } else {",
                        "       dest.writeByte((byte) 0);",
                        "     }",
                        "     if (source.mChar != null) {",
                        "       dest.writeByte((byte) 1);",
                        "       dest.writeList(source.mChar);",
                        "     } else {",
                        "       dest.writeByte((byte) 0);",
                        "     }",
                        "     if (source.mByte != null) {",
                        "       dest.writeByte((byte) 1);",
                        "       dest.writeList(source.mByte);",
                        "     } else {",
                        "       dest.writeByte((byte) 0);",
                        "     }",
                        "     if (source.mShort != null) {",
                        "       dest.writeByte((byte) 1);",
                        "       dest.writeList(source.mShort);",
                        "     } else {",
                        "       dest.writeByte((byte) 0);",
                        "     }",
                        "     if (source.mInt != null) {",
                        "       dest.writeByte((byte) 1);",
                        "       dest.writeList(source.mInt);",
                        "     } else {",
                        "       dest.writeByte((byte) 0);",
                        "     }",
                        "     if (source.mLong != null) {",
                        "       dest.writeByte((byte) 1);",
                        "       dest.writeList(source.mLong);",
                        "     } else {",
                        "       dest.writeByte((byte) 0);",
                        "     }",
                        "     if (source.mFloat != null) {",
                        "       dest.writeByte((byte) 1);",
                        "       dest.writeList(source.mFloat);",
                        "     } else {",
                        "       dest.writeByte((byte) 0);",
                        "     }",
                        "     if (source.mDouble != null) {",
                        "       dest.writeByte((byte) 1);",
                        "       dest.writeList(source.mDouble);",
                        "     } else {",
                        "       dest.writeByte((byte) 0);",
                        "     }",
                        "   }",
                        "",
                        "   @Override",
                        "   public void receive(final Model target, final android.os.Parcel in) {",
                        "     if (in.readByte() == 1) {",
                        "       target.mBoolean = new java.util.ArrayList<>();",
                        "       in.readList(target.mBoolean, java.util.List.class.getClassLoader());",
                        "     }",
                        "     if (in.readByte() == 1) {",
                        "       target.mChar = new java.util.ArrayList<>();",
                        "       in.readList(target.mChar, java.util.List.class.getClassLoader());",
                        "     }",
                        "     if (in.readByte() == 1) {",
                        "       target.mByte = new java.util.ArrayList<>();",
                        "       in.readList(target.mByte, java.util.List.class.getClassLoader());",
                        "     }",
                        "     if (in.readByte() == 1) {",
                        "       target.mShort = new java.util.ArrayList<>();",
                        "       in.readList(target.mShort, java.util.List.class.getClassLoader());",
                        "     }",
                        "     if (in.readByte() == 1) {",
                        "       target.mInt = new java.util.ArrayList<>();",
                        "       in.readList(target.mInt, java.util.List.class.getClassLoader());",
                        "     }",
                        "     if (in.readByte() == 1) {",
                        "       target.mLong = new java.util.ArrayList<>();",
                        "       in.readList(target.mLong, java.util.List.class.getClassLoader());",
                        "     }",
                        "     if (in.readByte() == 1) {",
                        "       target.mFloat = new java.util.ArrayList<>();",
                        "       in.readList(target.mFloat, java.util.List.class.getClassLoader());",
                        "     }",
                        "     if (in.readByte() == 1) {",
                        "       target.mDouble = new java.util.ArrayList<>();",
                        "       in.readList(target.mDouble, java.util.List.class.getClassLoader());",
                        "     }",
                        "   }",
                        "}"
                ));


        assertAbout(javaSource()).that(source)
                .processedWith(new PostmanProcessor())
                .compilesWithoutError()
                .and()
                .generatesSources(expectedSource);
    }



}
